[package]
authors = ["Colin Stearns <cstearns@developers.wyyerd.com>"]
name = "opa"
version = "0.1.0"
[dependencies]
failure = "0.1.5"
futures = "0.1"
reqwest = "0.9.5"
serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"
tokio = "0.1"
try_future = "0.1.3"
